### ISSUE TITLE
is stable the srtdroid ?

### ISSUE THREAD

**Issue by Allan-Nava** [ThibaultBee/srtdroid#16]
And can you display the srt ?

**Comment by ThibaultBee** [comment]
I am not sure, I understand your questiosn.
srtdroid v1.0.0 is based on SRT v1.4.2 (see [Changelog](https://github.com/ThibaultBee/srtdroid/releases/tag/1.0.0)).

The master of this repo is based on SRT v1.4.3 rc.1 (I am waiting the official v1.4.3 to tag srtdroid).

**Comment by Allan-Nava** [comment]
> I am not sure, I understand your questiosn.
> srtdroid v1.0.0 is based on SRT v1.4.2 (see [Changelog](https://github.com/ThibaultBee/srtdroid/releases/tag/1.0.0)).
> 
> The master of this repo is based on SRT v1.4.3 rc.1 (I am waiting the official v1.4.3 to tag srtdroid).

is there any example app ? 

And how can you watch the srt files, because exoplayer right now doesn't support this format

**Comment by ThibaultBee** [comment]
You will find example in [chat](https://github.com/ThibaultBee/srtdroid/tree/master/chat) and [examples](https://github.com/ThibaultBee/srtdroid/tree/master/examples).

But I guess you misunderstand SRT purpose. SRT purpose is only to transmit data with the higher possible bitrate. You can see it as an improved UDP Socket. It does not transmit video or audio unless you tell it to transmit video or audio. You should read documentation on SRT.

Also, I am working for a live streaming SDK based on SRT. It is private repository because it is still a WIP. To watch the stream result, I build ffmpeg with libsrt.

**Comment by Allan-Nava** [comment]
> You will find example in [chat](https://github.com/ThibaultBee/srtdroid/tree/master/chat) and [examples](https://github.com/ThibaultBee/srtdroid/tree/master/examples).
> 
> But I guess you misunderstand SRT purpose. SRT purpose is only to transmit data with the higher possible bitrate. You can see it as an improved UDP Socket. It does not transmit video or audio unless you tell it to transmit video or audio. It is not a container nor file format. You should read documentation on SRT.
> 
> Also, I am working for a live streaming SDK based on SRT. It is private repository because it is still a WIP. To watch the stream result, I build ffmpeg with libsrt.

You are right! Cause i'm trying to stream with srt like https://obsproject.com/wiki/Streaming-With-SRT-Protocol

**Comment by ThibaultBee** [comment]
Ok. I only have tested the other way (from phone to a FFmpeg server).
Haivison has a free SRT player for Android.
If you want a player in your application, you will have to read SRT stream, demux MPEGTS frames, decode A/V frames... it is not that easy! Unless you create your own solution, I don't see any solution right now.

**Comment by Allan-Nava** [comment]
> Ok. I only have tested the other way (from phone to a FFmpeg server).
> Haivison has a free SRT player for Android.
> If you want a player in your application, you will have to read SRT stream, demux MPEGTS frames, decode A/V frames... it is not that easy! Unless you create your own solution, I don't see any solution right now.

Haivision has implement sdk for SRT Player? 
And to publish your stream like rtmp ?

**Comment by ThibaultBee** [comment]
> Haivision has implement sdk for SRT Player?
You should check with them, but I haven't seen anything like this.

> And to publish your stream like rtmp ?
Do you mean stream from a Android phone to an SRT server?

**Comment by Allan-Nava** [comment]
> Do you mean stream from a Android phone to an SRT server?

Correctly!!


> You should check with them, but I haven't seen anything like this.
I found something but is bugged: https://github.com/Edward-Wu/liteplayer-srt

**Comment by ThibaultBee** [comment]
> > You should check with them, but I haven't seen anything like this.
> 
> I found something but is bugged: https://github.com/Edward-Wu/liteplayer-srt

I think this one is based on FFmpeg Android. It can be a solution.

> > Do you mean stream from a Android phone to an SRT server?
> 
> Correctly!!

FFmpeg Android can be a solution too. Also, my SRT live streaming SDK could be another solution.

**Comment by Allan-Nava** [comment]
> FFmpeg Android can be a solution too. Also, my SRT live streaming SDK could be another solution.

Perfect I try for sure! And it works correctly ? If i wanna stream to a specific srt server 



> I think this one is based on FFmpeg Android. It can be a solution.

The problem of this sdk it cannot compile, but if you want to create a sdk video player, let me know I can help you.

**Comment by ThibaultBee** [comment]
> The problem of this sdk it cannot compile, but if you want to create a sdk video player, let me know I can help you.
I do not plan to create a SRT video player SDK for now. I understand liteplayer does not compile, what I mean is that you can find FFmpeg Android solution on github.

**Comment by Allan-Nava** [comment]
> I do not plan to create a SRT video player SDK for now. I understand liteplayer does not compile, what I mean is that you can find FFmpeg Android solution on github.

Mmmmh I will try, for now I think I need to stream srt like this -> https://github.com/pedroSG94/rtmp-rtsp-stream-client-java

**Comment by ThibaultBee** [comment]
Good luck with this :)

**Comment by Allan-Nava** [comment]
> Good luck with this :)
> It seems to me that you are looking for something else than a SRT wrapper.
> Can I close this issue?

Yeah you can close this issue, but you think it is possible to stream to srt server ?

**Comment by ThibaultBee** [comment]
Technicaly, it is possible to stream MPEGTS+SRT from an Android device to an SRT server.
Unfortunately as player/streamer SDK might not exist yet, you will have to keep looking for solutions.

**Comment by Allan-Nava** [comment]
> Technicaly, it is possible to stream MPEGTS+SRT from an Android device to an SRT server.
> Unfortunately as player/streamer SDK might not exist yet, you will have to keep looking for solutions.

Ok, i saw larix broadcaster https://softvelum.com/larix/ , do you know how can we create something like that?

**Comment by ThibaultBee** [comment]
You can purchase their SDK.
Otherwise, as I already said, free player/streamer SDK might not exist yet. You should develop it.
