### ISSUE TITLE
how to use the lib send byte array

### ISSUE THREAD

**Issue by wangpeng1** [ThibaultBee/srtdroid#24]
i want to use the lib send rtmp date, but the demo is not the send byte array api.

**Comment by ThibaultBee** [comment]
Hi,
This is not a RTMP library. To send ByteArray, you should check the API guide: https://thibaultbee.github.io/srtdroid/lib/com.github.thibaultbee.srtdroid.models/-socket/index.html#-1156002596%2FFunctions%2F1946847589
