### ISSUE TITLE
Run failed

### ISSUE THREAD

**Issue by chenguo123456** [ThibaultBee/srtdroid#26]
When I download the code, an error is reported! Please give us your advice and look forward to your reply! thank you!
1.Execution failed for task ':lib:buildCMakeDebug[arm64-v8a]'.
2.Execution failed for task ':lib:buildCMakeDebug[armeabi-v7a]'.
3.Execution failed for task ':lib:buildCMakeDebug[x86]'.
4.Execution failed for task ':lib:buildCMakeDebug[x86_64]'.
![image](https://user-images.githubusercontent.com/88373004/197105191-d084c3c4-64d2-40ab-8989-ad63d143898d.png)
![image](https://user-images.githubusercontent.com/88373004/197105221-1696611a-cb60-42c5-abbb-efedbb083768.png)
![image](https://user-images.githubusercontent.com/88373004/197105273-0dd601b0-627c-4a0d-b843-42903921ff1a.png)

**Comment by ThibaultBee** [comment]
Hi,

It seems that you failed to clone openssl repo at the time of the build.
Building srtdroid is the really complex process, do you really need to buld it?

**Comment by chenguo123456** [comment]
Thank you for your reply. I need to use SRT transmission! Can you help me solve it? thank you




Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/srtdroid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月21日(星期五) 下午2:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/srtdroid] Run failed (Issue #26)





 
Hi,
 
It seems that you failed to clone openssl repo at the time of the build.
 Building srtdroid is the really complex process, do you really need to buld it?

**Comment by ThibaultBee** [comment]
Hi,

To use srtdroid, look at https://github.com/ThibaultBee/srtdroid#install
Then you must create a `Socket` from srtdroid package.

By the way, I never suceed to build the project on Windows (see https://github.com/ThibaultBee/srtdroid#windows)

**Comment by chenguo123456** [comment]
Thank you for your reply.
I&nbsp; just use srt on android ,just your examples,
Can you give me some advice?
thank you!


Roman
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThibaultBee/srtdroid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月22日(星期六) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThibaultBee/srtdroid] Run failed (Issue #26)





 
Hi,
 
To use srtdroid, look at https://github.com/ThibaultBee/srtdroid#install
 Then you must create a Socket from srtdroid package.
 
By the way, I never suceed to build the project on Windows (see https://github.com/ThibaultBee/srtdroid#windows)

**Comment by chenguo123456** [comment]
this  https://github.com/ThibaultBee/srtdroid#install Can 4G transmission be used? thank you

**Comment by ThibaultBee** [comment]
SRT and srtdroid does not make a difference between any network link. So yes.
