### ISSUE TITLE
how to use MsgCtrl

### ISSUE THREAD

**Issue by wangpeng1** [ThibaultBee/srtdroid#27]
Hi， i used the project and streampack，it used the MsgCtrl  when thranslate live streaming。
but i donot want use  send method,i want to use  srtSocket.getInputStream(null) and srtSocket.getOutputStream(null), I have a lot of confusion and need your help：
1. I used the live mode by rtmp over srt, whether the MsgCtrl parameter of getInputStream or getOutputStream can be passed empty？
2. I used the live mode by mpegts over srt, whether each package must accurately transmit the MsgCtrl package information ？

**Comment by ThibaultBee** [comment]
Hi,

Both `getInputStream` and `getOutputStream` support a `null` MsgCtrl. If MsgCtrl shoud be set or not depends on what you want to achieve.

If you have questions about MsgCtrl, you should have a look on the SRT structure: https://github.com/Haivision/srt/blob/master/docs/API/API-functions.md#SRT_MSGCTRL

In a general way, if you have specific question for the usage of SRT, you should refer to SRT documentation. This project is only a wrapper around SRT and does not bring anything else. Moreover, in srtdroid API guide, there is often a link to the SRT function/structure behind.
