### ISSUE TITLE
srtcore/core.cpp@6491:sendmsg2 14:54:30.657568/Thread-60*E:SRT.as: INVALID: Data size for sending declared with length: 0

### ISSUE THREAD

**Issue by wangpeng1** [ThibaultBee/srtdroid#28]
i put the aar in my android  java project, the connect is correct,but when i call send()  method,it give me the error

**Comment by wangpeng1** [comment]
Sometimes when i call send()method  it give me:  java.net.SocketTimeoutException: Connection setup failure: socket closed during operation.

**Comment by ThibaultBee** [comment]
Hi,
Could you share how you use `send()` (with the ByteBuffer or the ByteArray)?

About the second exception, it is explicit: the socket has been closed.

**Comment by wangpeng1** [comment]
Hi,                                                                                                                                                                                             
  in my java android project ,when,i used send(ByteBuffer)  it give me   java.net.SocketTimeoutException: Connection setup failure: socket closed during operation.
when i used send(ByteBuffer.array()) it give me Operation not supported: Incorrect use of Message API (sendmsg/recvmsg).

when i used srtSocket.getOutputStream(null).write(buffer.array());  it is ok.

but in your kotlin project,all is ok.

**Comment by ThibaultBee** [comment]
So, you don't face the first issue anymore?

I believe the only issue you face is that you are trying to use message API with an incorrect size of buffer. Either:
- use a buffer with the correct size
- use stream API
Please refer to the SRT documentation for more info.
