### ISSUE TITLE
How often to send a SDT PMT PAT？

### ISSUE THREAD

**Issue by wangpeng1** [ThibaultBee/srtdroid#29]
Hi，
    i need your some help， How often to send a SDT PMT PAT？Whether to send PMT  PAT when key frame？ what is the advantage of doing this？ Is there any document that can be queried？ thank you

**Comment by ThibaultBee** [comment]
Hi,

This is not a question related to srtdroid as srtdroid is just a wrapper around SRT (which is a communication protocol).
Please contact streaming video experts.

Best regards,
Thibault
