### ISSUE TITLE
I am getting build command failed issue when I am syncing this project in my system 

### ISSUE THREAD

**Issue by shailendrapokhriyal96** [ThibaultBee/srtdroid#4]
Build command failed.
Error while executing process /home/pmsl/Android/Sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/pmsl/Vickey/OTTProjects/R&D/SRTWrapper-master/lib/.cxx/cmake/debug/armeabi-v7a jnisrt}
ninja: Entering directory `/home/pmsl/Vickey/OTTProjects/R&D/SRTWrapper-master/lib/.cxx/cmake/debug/armeabi-v7a'
[1/20] Creating directories for 'openssl_project'
[2/20] Performing download step (download, verify and extract) for 'openssl_project'
-- File already exists but no hash specified (use URL_HASH):
  file='/home/pmsl/Vickey/OTTProjects/R&D/SRTWrapper-master/lib/.cxx/cmake/debug/armeabi-v7a/openssl_project-prefix/src/openssl-1.1.1f.tar.gz'
Old file will be removed and new file downloaded from URL.
-- Downloading...
   dst='/home/pmsl/Vickey/OTTProjects/R&D/SRTWrapper-master/lib/.cxx/cmake/debug/armeabi-v7a/openssl_project-prefix/src/openssl-1.1.1f.tar.gz'
   timeout='none'
-- Using src='https://www.openssl.org/source/openssl-1.1.1f.tar.gz'
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- Downloading... done
-- extracting...
     src='/home/pmsl/Vickey/OTTProjects/R&D/SRTWrapper-master/lib/.cxx/cmake/debug/armeabi-v7a/openssl_project-prefix/src/openssl-1.1.1f.tar.gz'
     dst='/home/pmsl/Vickey/OTTProjects/R&D/SRTWrapper-master/lib/.cxx/cmake/debug/armeabi-v7a/openssl_project-prefix/src/openssl_project'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[3/20] No patch step for 'openssl_project'
[4/20] No update step for 'openssl_project'
[5/20] Performing configure step for 'openssl_project'
Configuring OpenSSL version 1.1.1f (0x1010106fL) for android-arm
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   OpenSSL has been successfully configured                     ***
***                                                                ***
***   If you encounter a problem while building, please open an    ***
***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
***   and include the output from the following command:           ***
***                                                                ***
***       perl configdata.pm --dump                                ***
***                                                                ***
***   (If you are new to OpenSSL, you might want to consult the    ***
***   'Troubleshooting' section in the INSTALL file first)         ***
***                                                                ***
**********************************************************************
[6/20] Performing build step for 'openssl_project'
FAILED: openssl_project-prefix/src/openssl_project-stamp/openssl_project-build /home/pmsl/Vickey/OTTProjects/R&D/SRTWrapper-master/lib/build/intermediates/cmake/debug/obj/armeabi-v7a/libssl.so /home/pmsl/Vickey/OTTProjects/R&D/SRTWrapper-master/lib/build/intermediates/cmake/debug/obj/armeabi-v7a/libcrypto.so 
cd "/home/pmsl/Vickey/OTTProjects/R&D/SRTWrapper-master/lib/.cxx/cmake/debug/armeabi-v7a/openssl_project-prefix/src/openssl_project" && /home/pmsl/Android/Sdk/cmake/3.10.2.4988404/bin/cmake -E env PATH=/home/pmsl/Android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/linux-x86_64/bin:/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin ANDROID_NDK_HOME=/home/pmsl/Android/Sdk/ndk/20.0.5594570 make && /home/pmsl/Android/Sdk/cmake/3.10.2.4988404/bin/cmake -E touch "/home/pmsl/Vickey/OTTProjects/R&D/SRTWrapper-master/lib/.cxx/cmake/debug/armeabi-v7a/openssl_project-prefix/src/openssl_project-stamp/openssl_project-build"
No such file or directory
ninja: build stopped: subcommand failed.

**Comment by ThibaultBee** [comment]
Hi,

Do you have to rebuild the project ?
If you don't have to build the project, you should use https://jitpack.io/#ThibaultBee/SRTWrapper
Is something missing in this project ?

Anyway, what command do you use ?
Did you install 'make' ?

**Comment by ThibaultBee** [comment]
No news on this issue.

-> Closing this issue.
